site_name: app_utils
site_description: A starter project to create a standalone TDD project with docker based postgresql fixtures 

theme:
    name: 'readthedocs'

repo_name: redcarpetup/app_utils
repo_url: https://github.com/redcarpetup/app_utils

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - Examples: 'examples.md'
    - Roadmap: 'roadmap.md'

markdown_extensions:
  - codehilite
  - admonition
