site_name: rush
site_description: A starter project to create a standalone TDD project with docker based postgresql fixtures 

theme:
    name: 'readthedocs'

repo_name: redcarpetup/rush
repo_url: https://github.com/redcarpetup/rush

nav:
    - Introduction: 'index.md'
    - Quickstart: 'quickstart.md'
    - Examples: 'examples.md'
    - Roadmap: 'roadmap.md'

markdown_extensions:
  - codehilite
  - admonition
